### ISSUE TITLE
Transpose doesn't transpose root note of chord

### ISSUE THREAD

**Issue by lukeganzevoort** [cullub/Tabs-Lite#67]
I noticed when I transpose a song, the root notes of the chords don't get transposed.

For example A/C# becomes A#/C#, then G/C# and so on when transposing up.

**Comment by cullub** [comment]
Great find!  That should be fairly simple to fix; I'll get around to that in the next week or two.

**Comment by cullub** [comment]
Just fixed this in code; expect an update from Google Play fairly soon.
