### ISSUE TITLE
Favorites search/multi-select to playlist. Small search-related bug.

### ISSUE THREAD

**Issue by vidiia** [cullub/Tabs-Lite#71]
Thanks for this app, it's really incredible. Please consider some of these improvements to make it even better. Also noting a small bug.

- Make it possible to multi-select tabs from the favorites list to batch add them to a playlist.
- Make it possible to search/filter the favorites list instead of the search function being just for the whole UG database.

Bug: searching for a song you've already favorited shows it with an empty heart, as if you haven't favorited it. Makes it hard to know if you've already saved a song or not.

Thanks again. Your app is miles better than UG's offerings, so I use it all the time. Now I have a huge, unwieldy list I can't search or easily sort into playlists. I can handle these quirks, but if you solved them it would be even better.

**Comment by cullub** [comment]
Hi there, thanks for the kind words!  Those are great suggestions, I'll try to implement those when I get around to the next update!

Good catch on that bug.  I'm sure that won't be too hard to fix, so I'll prioritize that.

**Comment by cullub** [comment]
Separate issues created for each item so I can track the progress separately.

- #72 (bug)
- #47 (show favorite tabs in search suggestions)
- #73 (multi-select)

Feel free to watch those individual tasks for updates if you'd like.
